/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/components/breadcrumb.vue')['default']
    Detail: typeof import('./src/components/detail.vue')['default']
    Dialog: typeof import('./src/components/dialog.vue')['default']
    FileItem: typeof import('./src/components/fileItem.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    Overview: typeof import('./src/components/overview.vue')['default']
    RightMenu: typeof import('./src/components/rightMenu.vue')['default']
    TAlert: typeof import('tdesign-vue-next')['Alert']
    TButton: typeof import('tdesign-vue-next')['Button']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TInput: typeof import('tdesign-vue-next')['Input']
  }
}
